### ISSUE TITLE
Does it can using on Xtion?

### ISSUE THREAD

**Issue by Kn15263ss** [ThundeRatz/ros_yolo2#11]
Hi~ I have a little another problem...
I want to using Xtion to detecting object, and I don't know how to change the node of "uvc_camera/CameraNodelet".
Thanks you!!

**Comment by tiagoshibata** [comment]
Hi! [See this link to remap arguments](http://wiki.ros.org/Remapping%20Arguments) when launching from the command line, and [this link when using a launchfile](http://wiki.ros.org/roslaunch/XML/remap).

**Comment by Kn15263ss** [comment]
The link cannot connect.  ORZ

**Comment by tiagoshibata** [comment]
Both links work for me, maybe they are blocked in your region?
