### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by royaalto** [ThundeRatz/ros_yolo2#12]
I use ubuntu16.04 and kinetic ,cuda 9.0, launch the sample with my yolo.cfg and yolo.weights get this error

[FATAL] [1509699431.787032764]: Failed to load nodelet '/vision/yolo2` of type `yolo2/Yolo2Nodelet` to manager `vision_nodelet'
[vision/vision_nodelet-2] process has died [pid 7147, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=vision_nodelet __log:=/home/roy/.ros/log/f85af0ac-c074-11e7-8696-e09467d4173c/vision-vision_nodelet-2.log].
log file: /home/roy/.ros/log/f85af0ac-c074-11e7-8696-e09467d4173c/vision-vision_nodelet-2*.log
[vision/yolo2-4] process has died [pid 7149, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load yolo2/Yolo2Nodelet vision_nodelet yolo2/image:=image_raw __name:=yolo2 __log:=/home/roy/.ros/log/f85af0ac-c074-11e7-8696-e09467d4173c/vision-yolo2-4.log].
log file: /home/roy/.ros/log/f85af0ac-c074-11e7-8696-e09467d4173c/vision-yolo2-4*.log

I am new to Ros , do you know the solution?

**Comment by tiagoshibata** [comment]
Did you build the nodelet before launching?

Logs or a stacktrace would be very appreciated.

**Comment by tiagoshibata** [comment]
Please try building the nodelet before launching the nodelet server. Let me know if you have more problems. I'll close the issue if it remains stale.
