### ISSUE TITLE
How to determine whether cudnn is used or not?

### ISSUE THREAD

**Issue by DanLiu0623** [ThundeRatz/ros_yolo2#14]
I use your cmakelists, but I found the fps does't increase, so how can I determine if the cudnn is used or not.Thank you very much~

**Comment by tiagoshibata** [comment]
There's a CMake option to enable cuDNN: [CMakeLists.txt](https://github.com/ThundeRatz/ros_yolo2/blob/master/CMakeLists.txt#L4). You can use `-D` flags in `cmake` invocation or `ccmake`/`cmake-gui` to set it.

**Comment by DanLiu0623** [comment]
Yes,I enable it, but it seems does not work because I could not see and increase of fps.

**Comment by tiagoshibata** [comment]
You're right, `cudnn` is missing in the `target_link_libraries` statement. The code will compile with cuDNN support, but the library is not being linked. It should be [a simple fix here](https://github.com/ThundeRatz/ros_yolo2/blob/d750ad760d11fb8e248cc356456d16d6ad87cb30/CMakeLists.txt#L128-L129). I can take a look at it in the next days and test it.

But I'm curious: do you have a source showing that YOLOv2 or YOLO9000 is faster with cuDNN? If memory serves me well, there were problems using cuDNN (no noticeable improvement or some buggy results), and [I see people having trouble with it](https://groups.google.com/forum/#!topic/darknet/duRWDd5MN94).

**Comment by tiagoshibata** [comment]
@erickotsuka @Dupletor Might be worth benchmarking in a Tegra. I'll look into the fix, but I'll keep the current default value (cuDNN off) until there's proof that cuDNN makes YOLO faster.

**Comment by tiagoshibata** [comment]
Proposed fix is at #15 . I tested building and linking with kinetic and CUDA 9.1/cuDNN 7, linkage is correct now. It seems right, but I didn't test the inference (I don't have a trained model at reach right now). Let me know if it works for you!
