### ISSUE TITLE
error: too few arguments

### ISSUE THREAD

**Issue by wolf943134497** [ThundeRatz/ros_yolo2#6]
/src/darknet/yolo2.cpp:123:93: error: too few arguments to function ‘void get_region_boxes(layer, int, int, float, float**, box*, int, int*, float)’
     get_region_boxes(output_layer, 1, 1, min_confidence_, probs_.data(), boxes_.data(), 0, 0);
                                                                                             ^
In file included from /home/gwm/catkin_ws/src/ros_yolo2/src/darknet/yolo2.cpp:42:0:
/home/gwm/catkin_ws/src/ros_yolo2/darknet/src/region_layer.h:10:6: note: declared here
 void get_region_boxes(layer l, int w, int h, float thresh, float **probs, box *boxes, int only_objectness, int *map, float tree_thresh);
Need 9  arguments

**Comment by tiagoshibata** [comment]
I don't see the `tree_thresh` parameter on commit 2710d632571a0083f6b8aa57a3c822b57a9f4866 (the one that's set as the submodule): [darknet@2710d632571a0083f6b8aa57a3c822b57a9f4866/src/region_layer.h](https://github.com/pjreddie/darknet/blob/2710d632571a0083f6b8aa57a3c822b57a9f4866/src/region_layer.h)

You probably ran an update on the submodules, which pulled this change: [b3c4fc9f223d9b6f50a1652d8d116fcdcc16f2e8](https://github.com/pjreddie/darknet/commit/b3c4fc9f223d9b6f50a1652d8d116fcdcc16f2e8#diff-1ec3cb7f37df1091272e11c83dc2bbcbR12). They did a breaking change to the function arguments. I'll take a look at it some time to make it compatible with the newer darknet commit, but you can still build ros_yolo2 by keeping the current submodule commit (not running `git submodule update` before build).

Let me know if you have further problems, else I'll close this issue.

**Comment by wolf943134497** [comment]
@tiagoshibata  Thanks a lot .I will try a old darknet version.

**Comment by tiagoshibata** [comment]
OK, `git clone --recursive git@github.com:ThundeRatz/ros_yolo2.git` should do it.
