### ISSUE TITLE
catkin_make error: cannot convert ‘box*’ to ‘float’

### ISSUE THREAD

**Issue by Kanelankai** [ThundeRatz/ros_yolo2#7]
I tried catkin_make the package, however I have this error:

/home/dasmain/catkin_ws/src/yolo2/src/darknet/yolo2.cpp:123:71: error: invalid conversion from ‘float**’ to ‘int’ [-fpermissive]
     get_region_boxes(output_layer, 1, 1, min_confidence_, probs_.data(), boxes_.data(), 0, 0);
                                                                       ^
/home/dasmain/catkin_ws/src/yolo2/src/darknet/yolo2.cpp:123:93: error: cannot convert ‘box*’ to ‘float’ for argument ‘6’ to ‘void get_region_boxes(layer, int, int, int, int, float, float**, box*, int, int*, float, int)’
     get_region_boxes(output_layer, 1, 1, min_confidence_, probs_.data(), boxes_.data(), 0, 0);

Any advice or comments would be appreciated.
Thanks in advance.
@tiagoshibata

**Comment by tiagoshibata** [comment]
You're probably using the wrong darknet commit. There were breaking changes to the library, please don't update the submodule to the latest version.

#6 is related. Could you try cloning this repository with `--recursive ` and see if your issue persists?

**Comment by tiagoshibata** [comment]
Closing after a week, let me know if your issue persists and I'll reopen it.
